Payload gen seq experiment@0.6.0.1
icgc-argo-workflows/data-processing-utility-tools pull request #154
Opened 2022-08-03 21:28 UTC by edsu7

- Added support for `core` and `conditional`.
  - https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/baf295868c44739b367874251068b7511fee4db7/payload-gen-seq-experiment/main.py#L40-61
  - Should fail if core is not detected
- Fail if `library_strandedness` is not present if `experiment_type==RNA-seq`
  - https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/baf295868c44739b367874251068b7511fee4db7/payload-gen-seq-experiment/main.py#L328-L329
- Validation check against schema
  - https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/baf295868c44739b367874251068b7511fee4db7/payload-gen-seq-experiment/main.py#L179-246
  - Check wrong enum value in `platform`
  - Check wrong regex in `submitter_sequencing_experiment_id`
  - incorrect min max number in `rin`

2022-08-04 14:44 UTC, lindaxiang requested changes

2022-08-04 14:44 UTC, lindaxiang commented on payload-gen-seq-experiment/main.py
> +    url="https://raw.githubusercontent.com/icgc-argo/argo-metadata-schemas/master/schemas/sequencing_experiment.json"
Can we make schema `url` as an optional input? So that we can test the tool and schemas in QA/Dev environments when it is needed.

2022-08-04 14:44 UTC, lindaxiang commented on payload-gen-seq-experiment/main.py
> +def validatePayload(payload):
Do we consider to use external python package to do the payload validation upon with the schema?
For example: `from jsonschema import validate`(https://pypi.org/project/jsonschema/)

2022-08-04 19:50 UTC, edsu7 commented on payload-gen-seq-experiment/main.py
> +    url="https://raw.githubusercontent.com/icgc-argo/argo-metadata-schemas/master/schemas/sequencing_experiment.json"
Added url as a possible argument, if not specified will default
https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/b92149c17734e3d312669cccaad18fa3158610a1/payload-gen-seq-experiment/main.py#L338-339

https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/b92149c17734e3d312669cccaad18fa3158610a1/payload-gen-seq-experiment/main.py#L180-184

2022-08-04 19:53 UTC, edsu7 commented on payload-gen-seq-experiment/main.py
> +def validatePayload(payload):
Thanks for the great suggestion. Less headaches compared to what I was doing.
https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/b92149c17734e3d312669cccaad18fa3158610a1/payload-gen-seq-experiment/main.py#L180-197

Had to make some changes to the schema so it would validate correctly:
https://github.com/icgc-argo/argo-metadata-schemas/compare/master...seq_experiment_typo

2022-08-04 20:03 UTC, lindaxiang commented on payload-gen-seq-experiment/main.py
> +def validatePayload(payload):
wow, this is much neat! 👍

2022-08-04 20:19 UTC, lindaxiang commented on payload-gen-seq-experiment/main.py
> +    url="https://raw.githubusercontent.com/icgc-argo/argo-metadata-schemas/master/schemas/sequencing_experiment.json"
@edsu7 what if you validate the payload against the full schema:
https://submission-song.rdpc.cancercollaboratory.org/schemas/sequencing_experiment

2022-08-05 19:04 UTC, edsu7 commented on payload-gen-seq-experiment/main.py
> +    url="https://raw.githubusercontent.com/icgc-argo/argo-metadata-schemas/master/schemas/sequencing_experiment.json"
Updated default URL:
https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/81b46904f19517a4b41d427ea96e389c00358dd7/payload-gen-seq-experiment/main.py#L184

2022-08-09 15:42 UTC, lindaxiang commented on payload-gen-seq-experiment/main.nf
> +version = '0.6.0.1'
Should we also add `schema-url` as an optional input param in `main.nf`?

2022-08-09 15:42 UTC, lindaxiang commented on payload-gen-seq-experiment/main.py
> +
`sequencing_center` is defined in both `core` and `conditional`.

2022-08-09 17:14 UTC, edsu7 commented on payload-gen-seq-experiment/main.nf
> +version = '0.6.0.1'
Added
https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/1196d178af4e2894084413e4edbd565a241c1ca2/payload-gen-seq-experiment/main.nf#L91-L97

2022-08-09 17:15 UTC, edsu7 commented on payload-gen-seq-experiment/main.py
> +
Removed `sequencing_center` from `conditional`
https://github.com/icgc-argo-workflows/data-processing-utility-tools/blob/1196d178af4e2894084413e4edbd565a241c1ca2/payload-gen-seq-experiment/main.py#L46-L50

2022-08-09 19:12 UTC, lindaxiang approved these changes

2022-08-09 20:01 UTC, merged